class TaskError(ValueError):
    """
    Represents an error that occurs during the running of a tasks before, do or after task
    """

    pass